on:
  push:
    branches:
      - main
      - gh-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.7
        with:
          architecture: 'x64'
          distribution: 'full'
          version: '8.2'
          dest: '/opt/racket'
          sudo: never
          local_catalogs: $GITHUB_WORKSPACE
      - name: install dependencies
        run: raco pkg install --auto --no-docs racketscript
      - run: 'ls -al $GITHUB_WORKSPACE/'
      - name: compile site
        run: '$GITHUB_WORKSPACE/8.2/bin/racks main.rkt'
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: public
